### ISSUE TITLE
How to generate plugin-all.jar and how to publish the result of mirai- buildPlugin task?

### ISSUE THREAD

**Issue by Nambers** [Him188/maven-central-publish#7]
1. 怎么生成plugin-all.jar? 是用shadow任务先生成结果 然后改名成plugin-all.jar然后放到lib文件夹里吗？现在没自动生成然后报错:
```
gpg: can't open '\build\libs\plugin-2.7-RC-dev3-all.jar': No error
gpg: signing failed: System error w/o errno
```
2. 怎么发布buildPlugin task生成的mirai.jar? PeratX说要依赖那个task生成?

Thanks

**Comment by Nambers** [comment]
关于第二点，好像不能依赖buildPlugin? 
因为要先取到任务, 用 artifact(tasks.getByName("buildPlugin"))
然后buildPlugin好像是后来加的，要用afterEvaluate,
但是加了没效果

**Comment by Nambers** [comment]
第二点解决了(
把maven-publish插件在mirai-console后加载就好了
问题就是怎么自动生成\<name\>-\<version\>-all.jar?

**Comment by Him188** [comment]
> gpg: can't open '\build\libs\plugin-2.7-RC-dev3-all.jar': No error

会在 0.6.0 解决

> 怎么自动生成<name>-<version>-all.jar?

与 maven-central-publish 无关, 你可能要使用 shadow plugin

> 怎么发布buildPlugin task生成的mirai.jar

```kotlin
mavenCentralPublish {
    publication {
         artifact(tasks.getByName("buildPlugin"))
    }
}
```

**Comment by Nambers** [comment]
嗯 第一点和第三点都解决了，就第二点是要手动生成mirai.jar然后改成-all.jar复制进去吗?

**Comment by Him188** [comment]
> gpg: can't open '\build\libs\plugin-2.7-RC-dev3-all.jar': No error

该错误的原因不是缺少 "\build\libs\plugin-2.7-RC-dev3-all.jar", 而是应该忽略这个文件

**Comment by Nambers** [comment]
> > gpg: can't open '\build\libs\plugin-2.7-RC-dev3-all.jar': No error
> 
> 该错误的原因不是缺少 "\build\libs\plugin-2.7-RC-dev3-all.jar", 而是应该忽略这个文件

就原本是不需要这个文件存在的,然后下个版本修复
okok明白了

**Comment by Nambers** [comment]
可以了, 在0.6.1会skip -all.jar
